### ISSUE TITLE
2.4G for wireless works, 5G does not

### ISSUE THREAD

**Issue by lipinm** [privacylabs/oasis#5]

**Comment by girisreenivas** [comment]
Yes, that is correct. The Raspberry Pi 3 integrated WiFi only supports 2.4G:

https://www.raspberrypi.org/magpi/raspberry-pi-3-specs-benchmarks/

**Comment by lipinm** [comment]
btw, had to restart the EC2 server and then it all came back to life

**Comment by girisreenivas** [comment]
thanks for the heads up about that

**Comment by lipinm** [comment]
BTW, had to restart the EC2 server...then it all came up.

Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone

-------- Original message --------
